// Builds docs/rules.md: every Comprehensive Rules section the code cites, with the opening of
// its text and the files that cite it. Refuses a citation that does not exist in the rules text.
//   node tools/rules-index.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';
import { ROOT } from './load.mjs';
const rulesFile = path.join(ROOT, 'scratch/rules/MagicCompRules.txt');
if (!fs.existsSync(rulesFile)) { console.log('rules text missing: fetch it into scratch/rules/ (docs/sources.md)'); process.exit(2); }
const lines = fs.readFileSync(rulesFile, 'utf8').split(/\r?\n/);
const text = {};
for (const l of lines) { const m = l.match(/^(\d{3}\.\d+[a-z]?)\.? ([^]*)$/); if (m && !text[m[1]]) text[m[1]] = m[2]; }
const files = [];
const walk = d => { for (const f of fs.readdirSync(path.join(ROOT, d))) { const p = path.join(d, f); if (fs.statSync(path.join(ROOT, p)).isDirectory()) { if (!/^(scratch|node_modules|\.git|data|art|audio)$/.test(f)) walk(p); } else if (/\.(js|mjs)$/.test(f)) files.push(p.split(path.sep).join('/')); } };
walk('js'); walk('tools');
const cites = {};
for (const f of files) {
  const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
  for (const m of src.matchAll(/CR ((?:\d{3}\.\d+[a-z]?(?:-[a-z0-9.]+)?)(?:[,/ ]+(?:\d{3}\.\d+[a-z]?))*)/g)) {
    for (const n of m[0].slice(3).split(/[,/ ]+/)) { const k = n.replace(/-.*$/, ''); if (!/^\d{3}\.\d+[a-z]?$/.test(k)) continue; (cites[k] = cites[k] || new Set()).add(f); }
  }
}
const bad = Object.keys(cites).filter(k => !text[k]);
const key = k => { const [a, b] = k.split('.'); return +a * 1e6 + parseInt(b, 10) * 100 + (/[a-z]$/.test(b) ? b.charCodeAt(b.length - 1) - 96 : 0); };
const out = ['# Rules — citation index', '', 'Generated by `node tools/rules-index.mjs` from every `CR` comment in `js/` and `tools/`, against the',
  'Comprehensive Rules effective September 25, 2026 (`scratch/rules/MagicCompRules.txt`, docs/sources.md).',
  'A citation that does not exist in that text fails the generator.', '', '| Rule | Opening of the rule text | Cited in |', '|---|---|---|'];
for (const k of Object.keys(cites).sort((a, b) => key(a) - key(b))) {
  const t = (text[k] || 'NOT IN THE RULES TEXT').split('|').join('\\|');
  out.push(`| ${k} | ${t.length > 150 ? t.slice(0, 147) + '…' : t} | ${[...cites[k]].map(f => '`' + f + '`').join(' ')} |`);
}
if (!process.argv.includes('--check')) fs.writeFileSync(path.join(ROOT, 'docs/rules.md'), out.join('\n') + '\n');
if (bad.length) { console.log('rules-index: citations not in the rules text: ' + bad.join(', ')); process.exit(1); }
console.log(`rules-index: ${Object.keys(cites).length} sections cited, all present in the rules text`);
